image: cypress/browsers:node14.17.0-chrome88-ff89

pipelines:
  default:
    - step:
        name: Run Test
        caches:
          - node
        script:
          - npm ci
          - npm run test
        artifacts: 
          - cypress/screenshots/**